apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/jenkins-jenkins-agent: "true"
    jenkins/label-digest: "77f59de9a8723b4e82ba96d1ad98ff456e883631"
    jenkins/label: "jenkins-jenkins-agent_docker-azcli-kubectl"
  name: "docker-acr-k8s-agent-3f8v1"
  namespace: "jenkins"
spec:
  containers:
  - command:
    - "dockerd-entrypoint.sh"
    env:
    - name: "TEST_ACR_LOGIN_SERVER"
      value: "myrspovenai5promotest.azurecr.io"
    - name: "K8S_NAME"
      value: "optimizer-test"
    - name: "PROD_ACR_LOGIN_SERVER"
      value: "myrspovenai5promotest.azurecr.io"
    - name: "DOCKER_HOST"
      value: "tcp://localhost:2376"
    - name: "AZURE_TENANT_ID"
      value: "417f23ad-bfef-451c-895b-c6e2cc5bf3e5"
    - name: "K8S_RG"
      value: "DevOps"
    - name: "DOCKER_TLS_CERTDIR"
      value: "/certs"
    - name: "DOCKER_TLS_CLIENTDIR"
      value: "/certs/client"
    - name: "JENKINS_URL"
      value: "http://jenkins.jenkins.svc.cluster.local:8080/"
    image: "myrspovendevopskubernetescr.azurecr.io/library/docker:24.0.2-dind"
    imagePullPolicy: "IfNotPresent"
    name: "dind"
    resources:
      limits:
        memory: "8Gi"
        cpu: "2000m"
      requests:
        memory: "1Gi"
        cpu: "100m"
    securityContext:
      privileged: true
    tty: false
    volumeMounts:
    - mountPath: "/certs"
      name: "volume-0"
      readOnly: false
    - mountPath: "/var/lib/docker"
      name: "volume-1"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - args:
    - "********"
    - "docker-acr-k8s-agent-3f8v1"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "jenkins-agent.jenkins.svc.cluster.local:50000"
    - name: "PROD_ACR_LOGIN_SERVER"
      value: "myrspovenai5promotest.azurecr.io"
    - name: "DOCKER_HOST"
      value: "tcp://localhost:2376"
    - name: "AZURE_TENANT_ID"
      value: "417f23ad-bfef-451c-895b-c6e2cc5bf3e5"
    - name: "DOCKER_TLS_CERTDIR"
      value: "/certs"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "TEST_ACR_LOGIN_SERVER"
      value: "myrspovenai5promotest.azurecr.io"
    - name: "K8S_NAME"
      value: "optimizer-test"
    - name: "JENKINS_AGENT_NAME"
      value: "docker-acr-k8s-agent-3f8v1"
    - name: "K8S_RG"
      value: "DevOps"
    - name: "DOCKER_TLS_CLIENTDIR"
      value: "/certs/client"
    - name: "JENKINS_NAME"
      value: "docker-acr-k8s-agent-3f8v1"
    - name: "JENKINS_URL"
      value: "http://jenkins.jenkins.svc.cluster.local:8080/"
    image: "myrspovendevopskubernetescr.azurecr.io/jenkins/agent/docker-azcli-kubectl:1.213"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits:
        memory: "2Gi"
        cpu: "500m"
      requests:
        memory: "1Gi"
        cpu: "100m"
    tty: false
    volumeMounts:
    - mountPath: "/certs"
      name: "volume-0"
      readOnly: false
    - mountPath: "/var/lib/docker"
      name: "volume-1"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  nodeSelector:
    agentpool: "ai5misc"
  restartPolicy: "Never"
  serviceAccountName: "default"
  volumes:
  - emptyDir:
      medium: ""
    name: "volume-0"
  - name: "volume-1"
    persistentVolumeClaim:
      claimName: "jenkins-agent-pvc"
      readOnly: false
  - emptyDir:
      medium: ""
    name: "workspace-volume"
